name: Flutter

on:
  # Runs this action when you push on master
  push:
    branches: [ "master","develop" ]
  # Runs this when a PR against master is created
    paths-ignore:
      - "**/README.md"
      - "**/.env"
  pull_request:
    branches: [ "master","develop" ]

jobs:
  flutter_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.2'
      - name: Install dependencies
        run: flutter pub get
      
      # Verifies if the dart code is formatted well
      - name: Verify formatting
        run: dart format .

      - name: Analyze project source
        run: flutter analyze .

      # Runs unit test
      - name: Run tests
        run: flutter test